name = "rentshare"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rentshare-db"
database_id = "3a6e52c1-5c00-4e1f-9c01-91a24a84f134"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "rentshare-photos"

[triggers]
crons = ["*/15 * * * *"]
